require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rubygems/package_task'

task :default => :package

CLEAN << 'pkg' << 'rdoc'

gemspec = eval(File.read('commonwatir.gemspec'))
Gem::PackageTask.new(gemspec) do |p|
  p.gem_spec = gemspec
  p.need_tar = false
  p.need_zip = false
end
